language: java
jdk: openjdk8
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
env:
- version=8
- version=11
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make test-docker
deploy:
- provider: script
  script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
  edge: true
  on:
    tags: true
    condition: "$version = 8"
    branch: main
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: NGGQe8OMWfbAOM6O7odDHtY/UVdqJ6oLQzB96QlTNkGgbyINKdufHxHaiv0SC/w4alUzzs6gw1h2WCpxw1PPl+pnVAeSVLfvRLYQApCGigWF0s5AyfVxtoG7bZOQLhsddC1ldQr12G4zclew+7k+0bgra4ENkbvv1OGiQdPJ08U=
