language: java
jdk: openjdk8
before_install:
- echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import --batch || true
env:
- version=8
- version=11
script:
- make test-docker
deploy:
- provider: script
  script: mvn clean deploy --settings .maven.xml -DskipTests=true -B -U -Prelease
  edge: true
  on:
    tags: true
    condition: "$version = 8"
    branch: main
notifications:
  slack:
    if: branch = main
    on_pull_requests: false
    on_success: never
    on_failure: change
    rooms:
      secure: U60cRCUgX4z+CYZXW/DjNSeCr4rxZVJBjlsGtpzNVWt2Lz7jhx/6Bx/2SChPQt1BR/6RY3kUf1hXAd3vqbwIMjvSFm/HBb4EHEWLAoqVtHjj6p9YZ+NXFzxRrarG3tBB14prRoG2t8TwdcvxnklBOYgUY5PWld3ptp+BG8iyr8A=
